yarnPath: .yarn/releases/yarn-3.2.1.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

packageExtensions:
  "@nrwl/nx-cloud@*":
    dependencies:
      rxjs: "*"
