version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=flipcar
      - POSTGRES_PASSWORD=flipcar
      - POSTGRES_DB=flipcar
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
